# Generated by Django 5.2.7 on 2025-10-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(help_text='imagen de 1920 x 1080', upload_to='slider')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('boton', models.CharField(blank=True, max_length=30, null=True)),
                ('enlace_boton', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
