# Generated by Django 5.2.7 on 2025-10-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_indexofrecemos'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexofrecemos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
