# Generated by Django 5.2.7 on 2025-10-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_indexofrecemos_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexLineaProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(help_text='imagen de 386 x 330', upload_to='slider')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='indexofrecemos',
            name='imagen',
            field=models.ImageField(help_text='imagen de 386 x 330', upload_to='slider'),
        ),
    ]
